[package]
name = "cennznut"
version = "0.1.1"
authors = ["Centrality Developers <developers@centrality.ai>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
bit_reverse = { version = "0.1.7", default-features = false }

[features]
default = [ "std" ]
std = [
  "codec/std"
]
