[package]
name = "cennznut"
version = "0.1.0"
authors = ["Centrality Developers <developers@centrality.ai>"]
edition = "2018"

[dependencies]
parity-codec = { version = "3.5.1", default-features = false }
bit_reverse = { version = "0.1.7", default-features = false }
hashbrown = { version = "0.1.2", features = [ "nightly" ] }
