version: 2
jobs:
  built-and-tested:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - run: echo "successfully built and tested"
  build:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup component add rustfmt

            rustup install nightly
      - run:
          name: cargo check
          command: |
            cargo --version --verbose
            cargo check
      - run:
          name: cargo fmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: "Check 'no std' build"
          command: |
            cargo +nightly --version --verbose
            cargo +nightly check --no-default-features
      - run:
          name: Check JS build
          command: |
            # install npm + yarn + wasm-pack
            sudo apt install npm
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            # test js package build
            cd js && yarn
            yarn build
            yarn test
  test:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup install nightly
      - run:
          name: cargo test
          command: |
            cargo test
  clippy:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup component add clippy
            rustup install nightly
      - run:
          name: cargo clippy
          command: |
            cargo clean
            cargo clippy -- -D warnings
workflows:
  version: 2
  build-test-clippy:
    jobs:
      - build
      - test
      - clippy
      - built-and-tested:
          requires:
            - build
            - test
            - clippy

